---
# This playbook installs drush

- hosts: 127.0.0.1
  connection: local
  gather_facts: no

  roles:
    - { role: cibox-drush }

  vars:
    drush_composer_version: 8.*
    drush_git_version: 8.0.1
    drushrc:
      drush_usage_log: 1
      drush_usage_send: 1
      php-notices: warning
